-- ============================================================
-- SmartMenuKJ — Supabase setup (run ONCE)
-- Supabase → SQL Editor → New query → paste all of this → Run.
-- Creates the tables, security rules and auto-profile trigger
-- that power registration, contact inquiries, view analytics
-- and the admin panel.
--
-- The admin account is the email below (change it if needed):
--   krasimiruzun@smartmenukj.com
-- ============================================================

-- 1) Profiles — one row per registered user
create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  name text,
  email text,
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

-- 2) Contact inquiries
create table if not exists public.inquiries (
  id uuid primary key default gen_random_uuid(),
  name text,
  email text,
  phone text,
  service text,
  message text,
  created_at timestamptz not null default now()
);

-- 3) Page views
create table if not exists public.views (
  id bigint generated by default as identity primary key,
  path text,
  created_at timestamptz not null default now()
);

-- Helper: is the current user an admin? (security definer avoids RLS recursion)
create or replace function public.is_admin()
returns boolean language sql security definer stable as $$
  select coalesce((select is_admin from public.profiles where id = auth.uid()), false);
$$;

-- Auto-create a profile on sign-up and flag the owner as admin
create or replace function public.handle_new_user()
returns trigger language plpgsql security definer as $$
begin
  insert into public.profiles (id, name, email, is_admin)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'name', ''),
    new.email,
    case when lower(new.email) = lower('krasimiruzun@smartmenukj.com') then true else false end
  )
  on conflict (id) do nothing;
  return new;
end;
$$;
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- Enable Row Level Security
alter table public.profiles  enable row level security;
alter table public.inquiries enable row level security;
alter table public.views     enable row level security;

-- Profiles: a user reads their own row; admins read all
drop policy if exists "profiles_select" on public.profiles;
create policy "profiles_select" on public.profiles
  for select using (auth.uid() = id or public.is_admin());
drop policy if exists "profiles_insert" on public.profiles;
create policy "profiles_insert" on public.profiles
  for insert with check (auth.uid() = id);

-- Inquiries: anyone may submit; only admins may read
drop policy if exists "inquiries_insert" on public.inquiries;
create policy "inquiries_insert" on public.inquiries
  for insert with check (true);
drop policy if exists "inquiries_select" on public.inquiries;
create policy "inquiries_select" on public.inquiries
  for select using (public.is_admin());

-- Views: anyone may record a view; only admins may read
drop policy if exists "views_insert" on public.views;
create policy "views_insert" on public.views
  for insert with check (true);
drop policy if exists "views_select" on public.views;
create policy "views_select" on public.views
  for select using (public.is_admin());

-- Done. Next: copy your Project URL + anon key into config.js,
-- and (Authentication → Providers → Email) turn OFF "Confirm email".
